[watchdog]
version = "0.7.6"

# Key-value pairs that will be passed onto image as environment variables
# see https://github.com/openfaas/faas/tree/master/watchdog#delve-deeper
[watchdog.env]
fprocess = "./app.sh"
cgi_headers = "true"
